include $(THEOS)/makefiles/common.mk

APPLICATION_NAME = PkgHistory

PkgHistory_FILES = $(wildcard *.m)
PkgHistory_FRAMEWORKS = UIKit
PkgHistory_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/application.mk
